###### TABLE NIVEAUX USERS #####
CREATE TABLE niv_user (
  NIV_USER	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  XP_MAX			INT,
	ENDU_MAX			INT(5),
  EMP_TEAM_MAX			INT(5)
)
ENGINE=InnoDB;

###### TABLE USERS #####
CREATE TABLE users (
  ID_USER	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  PSEUDO			char(50) NOT NULL,
  EMAIL		char(70),
  MDP		char(12),
  NIVEAU			INT UNSIGNED NOT NULL,
	ENDU		INT,
  OR_			INT,
  ARGENT		INT,
  XP		INT,
CONSTRAINT fk_niveau_user
    FOREIGN KEY (NIVEAU)
    REFERENCES niv_user(NIV_USER)
)
ENGINE=InnoDB;

###### TABLE PERSOS #####
CREATE TABLE persos (
  ID_PERSOS	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOM			char(50) NOT NULL,
  TYPES		char(50) NOT NULL,
  TEAM		INT(1),
  VIE			INT(5),
  ATT			INT(5),
  DEF			INT(5),
  VIT			INT(5),
  PEN			INT(5),
  ARM			INT(5),
  PRE			INT(5),
  ESC			INT(5),
  CRIT		INT(5),
  TEN			INT(5),
  SOI			INT(5),
  Q_BASE			INT(1),
  STUFF_1		INT(2),
  STUFF_2		INT(2),
  STUFF_3		INT(2),
  EMP_TEAM			INT(3)
)
ENGINE=InnoDB;

###### TABLE BASE STUFF #####
CREATE TABLE base_stuff (
  ID_BASE_STUFF	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOM			char(50) NOT NULL,
  DESCR		char(255) NOT NULL,
	ATR_1			INT(5),
  ATR_2			INT(5),
  ATR_3			INT(5),
  TYPES			INT(1)
)
ENGINE=InnoDB;

###### TABLE NIVEAUX STUFF #####
CREATE TABLE niv_stuff (
  NIV_STUFF	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  XP_MAX			INT,
	UP_ATR_1			INT(5),
  UP_ATR_2			INT(5),
  COUT      INT(11)
)
ENGINE=InnoDB;

###### TABLE QUALITE STUFF #####
CREATE TABLE q_stuff (
  ID_Q_STUFF	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ETOILE			varchar(5) NOT NULL,
	UP_ATR_1			INT(5),
  UP_ATR_2			INT(5),
  NIV_MIN			INT
)
ENGINE=InnoDB;

###### TABLE STUFF #####
CREATE TABLE stuff (
  ID_STUFF	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NIVEAU			INT UNSIGNED NOT NULL,
  XP			INT,
	QUALITE			INT UNSIGNED NOT NULL,
  ID_BASE			INT UNSIGNED NOT NULL,
	ATR_1			INT(5),
  ATR_2			INT(5),
CONSTRAINT fk_niveau_stuff
    FOREIGN KEY (NIVEAU)
    REFERENCES niv_stuff(NIV_STUFF),
CONSTRAINT fk_q_stuff
    FOREIGN KEY (QUALITE)
    REFERENCES q_stuff(ID_Q_STUFF),
CONSTRAINT fk_base_stuff
    FOREIGN KEY (ID_BASE)
    REFERENCES base_stuff(ID_BASE_STUFF)
)
ENGINE=InnoDB;

###### TABLE NIVEAUX PERSO #####
CREATE TABLE niv_perso (
  NIV_PERSO	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  XP			INT,
  xp_min  INT,
  XP_MAX			INT,
  VIE			INT(5),
  ATT			INT(5)
)
ENGINE=InnoDB;

###### TABLE QUALITE PERSO #####
CREATE TABLE q_perso (
  ID_Q	INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ETOILE			INT(1),
  VIE			INT(5),
  ATT			INT(5),
  NIV_MIN			INT
)
ENGINE=InnoDB;

###### TABLE TEAM #####
CREATE TABLE team (
	ID_PERSO			INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ID_USER			INT UNSIGNED NOT NULL,
  ID_PERSOS			INT UNSIGNED NOT NULL,
  NIVEAU			INT UNSIGNED NOT NULL,
  XP			INT(5),
  QUALITE			INT UNSIGNED NOT NULL,
  TEAM			INT(1),
  STUFF_1			INT UNSIGNED NOT NULL,
  STUFF_2			INT UNSIGNED NOT NULL,
  STUFF_3			INT UNSIGNED NOT NULL,
  STUFF_4			INT(1),
  ETAT		char(50),
  pv_fight    INT(11),
CONSTRAINT fk_id_user
    FOREIGN KEY (ID_USER)
    REFERENCES users(ID_USER),
CONSTRAINT fk_id_persos
    FOREIGN KEY (ID_PERSOS)
    REFERENCES persos(ID_PERSOS),
CONSTRAINT fk_niveau_persos
    FOREIGN KEY (NIVEAU)
    REFERENCES niv_perso(NIV_PERSO),
CONSTRAINT fk_qualite_persos
    FOREIGN KEY (QUALITE)
    REFERENCES q_perso(ID_Q)
)
ENGINE=InnoDB;
